import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Al-Quran",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-red-400 dark:bg-[#0d1117] duration-700`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className={`max-w-[37rem] bg-white mx-auto min-h-screen`}>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
